spring:
  application:
    name: weatherpredictor
  data:
    redis:
      host: redis-17969.c244.us-east-1-2.ec2.redns.redis-cloud.com
      password: 5Ncxv9V4GqZ1bsBQLcGB2tgrpoANz0Ju
      ssl:
        enabled: true # Enable SSL if required
      timeout: 900 # expiry in sec
      port: 17969
server:
  address: 0.0.0.0
  port: 8080
weather:
  api:
    key: d2929e9483efc82c82c32ee7e02d563e
    url: https://api.openweathermap.org/data/2.5/forecast

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
